Auto test
KokiSakano/laravel8-vue pull request #8
Opened 2021-03-05 08:36 UTC by KokiSakano

テストケースの作成。

2021-03-11 02:19 UTC, 1t1nense1 reviewed
7点コメントさせていただきましたが、きちんと動作検証できていない部分もあるので、うまく動作しない部分などあったらコメントください 👍

2021-03-11 02:19 UTC, 1t1nense1 commented on laravel/tests/Feature/AuthenticationTest.php
> +    }
データが登録されたあと、指定のURIにリダイレクトされているかの確認であれば、以下のようにすると良いかなと思いました 👍 

そして、`$response = $this->get('get')`の部分は`トップページへアクセスできる`といった内容のテストとして切り出すと尚良いかと思いました 👍 

```suggestion
    /**
     * アクセス可能テスト
     */
    public function testAccess(): void
    {
        $response = $this->get('/');
        $response
            ->assertStatus(200);
    }

    /**
     * 登録テスト
     */
    public function testRegister(): void
    {
        $response = $this->post('/register', [
            'name' => $this->user['name'],
            'email' => $this->user['email'],
            'password' => $this->user['password'],
            'password_confirmation' => $this->user['password'],
        ]);

        // リダイレクト（302の検証）されているかの確認
        // リダイレクト先（route('home')でログイン後の遷移先URIが取得できる）の確認
        $response->assertStatus(Response::HTTP_FOUND)
            ->assertRedirect(route('home'));
    }
```

2021-03-11 02:19 UTC, 1t1nense1 commented on laravel/tests/Feature/AuthenticationTest.php
> +    }
![badge](https://img.shields.io/badge/review-imo-ff69b4.svg)
こちらは、ユーザーが登録されている上で認証が通るかのテストをしたいであれば、以下のように一度ユーザーを作成してから`login`に対してリクエストを投げると良いかと思います 👍 

```suggestion
    /**
     * ログイン認証テスト
     */
    public function testLogin(): void
    {
        // ユーザー登録
        User::factory()->create([
            'email' => $this->user['email'],
            'password' => \Hash::make($this->user['password']), // 標準のユーザー登録機能を利用する場合、パスワードをハッシュ化してDBに保存しているので
        ]);
        
        // 上で登録したユーザーとしてログイン
        $response = $this->post('/login', [
            'email' => $this->user['email'],
            'password' => $this->user['password'],
        ]);
        
        // ログイン後にhomeへリダイレクトされているかの確認
        $response->assertStatus(Response::HTTP_FOUND)
            ->assertRedirect(route('home'));
        
        // ログインできているかの確認    
        $this->assertAuthenticated();
    }
```

2021-03-11 02:19 UTC, 1t1nense1 commented on laravel/tests/Feature/AuthenticationTest.php
> +        $response->assertStatus(200);
![badge](https://img.shields.io/badge/review-imo-ff69b4.svg)
この部分いらないかもしれないです!

ログイン後もログアウト後も`/`には必ずアクセスできる仕様だと思うので、検証するなら`ログアウト後に / にリダイレクトされているか`を見た方が良いかなと思いました 👍 

```suggestion
        // ログアウト後にトップページへリダイレクトされているかの確認
        $response->assertStatus(Response::HTTP_FOUND)
            ->assertRedirect('/');
```

2021-03-11 02:19 UTC, 1t1nense1 commented on laravel/tests/Feature/AuthenticationTest.php
> +        $this->assertAuthenticated();
![badge](https://img.shields.io/badge/review-comment-yellow)
こんなメソッドあるの知りませんでした...。📝

2021-03-11 02:19 UTC, 1t1nense1 commented on laravel/tests/Feature/DatabaseTest.php
> +        $this->assertTrue($saveUser);
![badge](https://img.shields.io/badge/review-imo-ff69b4.svg)
以下のようにすると、データベースに意図したデータが存在するかを検証できるのでオススメです 👍 

```suggestion
        $this->assertTrue($saveUser);

        // userテーブルに、登録したデータが存在しているかの確認
        $this->assertDatabaseHas('users', [
            'name' => $testUser->name,
            'email' => $testUser->email,
        ]);
```

2021-03-11 02:19 UTC, 1t1nense1 commented on laravel/tests/Feature/UserTest.php
> +        $response -> assertStatus(200);
![badge](https://img.shields.io/badge/review-imo-ff69b4.svg)
`->`の両端にあるスペースが気になってしまいました...。

vscodeを使用しているのであれば、ファイル保存時に自動的に整形してくれる機能があるので、オススメです （[これ](https://m-gild.com/blog/1371)とか？）👍

2021-03-11 02:19 UTC, 1t1nense1 commented on laravel/tests/Feature/AuthenticationTest.php
> +    use RefreshDatabase;
アプリケーション側のDBもリフレッシュされてしまうと思うので、テスト用の環境を使った方が良いかも...と思いました。

[ここら辺](https://qiita.com/sola-msr/items/b317bb788f21dac176c4)を見ると、以下のファイルを弄ると実現できそうです（おそらくで申し訳ないです） 👍 

laravel/config/database.php
```php
'connections' => [
...
        'testing' => [
            'driver'   => 'sqlite',
            'database' => ':memory:', // SQLiteのインメモリ機能を使用
            'prefix'   => '',
            'options'  => [
                // テストデータの永続化
                PDO::ATTR_PERSISTENT => false,
            ],
        ],
```

laravel/.env.testing
```
DB_CONNECTION=testing
```

laravel/phpunit.xml
```xml
    <php>
        <server name="APP_ENV" value="testing"/>
        <server name="BCRYPT_ROUNDS" value="4"/>
        <server name="CACHE_DRIVER" value="array"/>
        <server name="MAIL_MAILER" value="array"/>
        <server name="QUEUE_CONNECTION" value="sync"/>
        <server name="SESSION_DRIVER" value="array"/>
        <server name="TELESCOPE_ENABLED" value="false"/>
    </php>
```

DB使わないので以下も必要ないかもしれないです（試してみてほしいです...）。

.github/workflows/laravel.yml
```yml
    env:
      APP_ENV: testing
      // DB_HOST: localhost
      // DB_PORT: 5432
      // PAGER: cat # prevent psql commands using less
```

2021-03-12 15:19 UTC, T-Kiyama approved these changes
いくつか指摘していますが、テスト内容は大丈夫だと思うので、approveしておきます！
改善できそうな箇所はたくさんあるので、時間のあるタイミングで対応してみてください！

2021-03-12 15:19 UTC, T-Kiyama commented on .github/workflows/laravel.yml
> +      #  working-directory: /home/runner/work/laravel8-vue/laravel8-vue/laravel
![意見、緩やかな指摘](https://img.shields.io/badge/review-imo-orange.svg)
もし不要そうであれば消してしまっていいと思います！

2021-03-12 15:19 UTC, T-Kiyama commented on laravel/tests/Feature/AuthenticationTest.php
> +use Tests\TestCase;
![意見、緩やかな指摘](https://img.shields.io/badge/review-imo-orange.svg)

useはアルファベット順にソートしていただけるとほんのちょっぴり読みやすくなります...！
(namespaceとuseの間はインデントあるとさらにいいと思います！）
```
namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Tests\TestCase;
```

2021-03-12 15:19 UTC, T-Kiyama commented on laravel/tests/Feature/AuthenticationTest.php
> +    public function testRegister():void
![typo等小さな指摘](https://img.shields.io/badge/review-nits-green.svg)
めちゃくちゃ細かいですが...!
タイプヒントにスペース欲しいです！
```
public function testRegister(): void
```

2021-03-12 15:19 UTC, T-Kiyama commented on laravel/tests/Feature/AuthenticationTest.php
> +            ->assertStatus(200);
![意見、緩やかな指摘](https://img.shields.io/badge/review-imo-orange.svg)
responseを別の箇所で使わない場合、ワンライナーで書いてしまっていいかなと思いました！
基本的にこういった生存期間が短い、一時的な変数は省略した方がみやすい傾向にあるので、是非意識してみてください！
```
$this->get('/')->assertStatus(200);
```

2021-03-12 15:19 UTC, T-Kiyama commented on laravel/tests/Feature/WhisperTest.php
> +<?php
他のテストでも使える内容なんですが、例えばこのWhisperTest.phpでは、全てのメソッドにて以下を実行していると思います。
```
$user = User::factory()->create();
$this->actingAs($user);
```

この場合、共通する処理はフィクスチャを使用して以下のようにしてあげるといいと思います！
```
namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

use App\Models\User;
use App\Models\Whisper;

class WhisperTest extends TestCase
{
    use RefreshDatabase;

    // テスト全体で共通する前準備の定義
    public function setUp(): void
    {
        parent::setUp();
        $user = User::factory()->create();
        $this->actingAs($user);

    }

    /**
     * 投稿テスト
     */
    public function testWhisperPost()
    {

        $response = $this->post('/api/whispers/', [
            'whisper' => 'test'
        ]);
        $response -> assertStatus(200);
        $this->assertEquals(1, Whisper::count());
    }

    /**
     * 削除テスト
     */
    public function testWhisperDelete()
    {
        $whisper = Whisper::factory()->create();

        $route = '/api/whispers/' . strval($whisper->id);
        $response = $this->delete($route);
        $response -> assertStatus(200);
        $this->assertEquals(0, Whisper::count());
    }

    /**
     * 取得テスト
     */
    public function testWhisperGet()
    {
        $whisper = Whisper::factory()->create();

        $response = $this->get('/api/whispers/');
        $response -> assertStatus(200);
    }
}
```
参考: https://phpunit.readthedocs.io/ja/latest/fixtures.html

2021-03-16 01:37 UTC, kei-s16 requested changes
レビューリクエストありがとうございます！

テスト内容については他の方がレビューしてくれているので、自動テスト部分についてのみレビューしました。
内容を確認したところ、自動テストが走らなくなっていたのでいったんRequest changesとさせてください。

内容はレビュー内容1点とコメント1点です。

自動テストが走らない理由はぱっと見テスト用のDBにアプリから繋げていないのが原因のように見えたので、その路線でコメントしています。コメント内容で試してみて動かなければお声がけください。
（Postgresに接続するための拡張が足りてないのかなーとも思ったんですが、[たぶん大丈夫そう](https://github.com/shivammathur/setup-php/wiki/Php-extensions-loaded-on-ubuntu-20.04#php-73)だったので……）

2021-03-16 01:37 UTC, k16em commented on .github/workflows/laravel.yml
> +      #  working-directory: /home/runner/work/laravel8-vue/laravel8-vue/laravel
https://github.com/KokiSakano/laravel8-vue/blob/5269fe337c8ce4f166f7698001f7bdf743d33729/.github/workflows/laravel.yml#L3-L7

今回の変更には直接関係ありませんが、この部分、合わせて`paths`も設定して、特定のファイルが変更された時のみテストが走るようにすると無駄なテストが走らなくなりかっこよくなると思います！

```
on:
  push:
    branches: [main]
    paths:
      - 'src/**' # Laravel関連のディレクトリに変更があった時にのみ処理が走る
      - 'src/!**.md' # ただし、変更されたファイルが *.mdの時は無視する（だいたいREADMEなので）
```
https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions

（今回の研修ではsrc以下に全部まとめている & publicリポジトリなので正直あまりやるメリットがありませんが、GitHub Actionsは無料 & プライベートなリポジトリだと月あたりの実行時間に制限があったりするので、個人開発のリポジトリなんかでやってみてください）

2021-03-16 01:37 UTC, k16em commented on .github/workflows/laravel.yml
> -        working-directory: /home/runner/work/laravel8-vue/laravel8-vue/laravel
![MUST](https://img.shields.io/badge/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC-MUST-critical)
ここ消すとActions上でテスト走らなくなっちゃいますね……

思いつきですし検証もしてないですが、↓のブロックに

https://github.com/KokiSakano/laravel8-vue/blob/5269fe337c8ce4f166f7698001f7bdf743d33729/.github/workflows/laravel.yml#L22-L26

↓を追記してみると動きませんかね？

```
DB_USERNAME=db_user
DB_PASSWORD=db_password
```

2021-03-17 00:36 UTC, KokiSakano commented
@T-Kiyama @kei-s16 @1t1nense1 
レビューありがとうございます。
ただいま拡張機能の一つの作成に手間取ってまして、それが終わり次第ご指摘の点変更させていただきます。

2021-03-17 05:02 UTC, KokiSakano commented
@T-Kiyama @kei-s16 @1t1nense1 
レビューして頂いた点改善致しました。また、自動テストも無事通るようになりました。

2021-03-17 22:48 UTC, kei-s16 approved these changes

2021-03-17 22:57 UTC, merged